### ISSUE TITLE
What is the library for math formulas formatting and editing?

### ISSUE THREAD

**Issue by hiangeel** [MichaelBykov/IntuitiveCalculator#1]
Hi,
I'm a newbie. I want to start learning Swift with a calculator app. Don't you mind to share information of the library that you used to format as well as edit math formulas?
Thank you so much.

**Comment by MichaelBykov** [comment]
Hey @hiangeel, I wrote all of the components of this application including all math formula evaluation, editing, and rendering by hand so I'm afraid I can't help you in respect to finding a suitable library because I didn't use one.
