### ISSUE TITLE
[Feature Request] Sigma and Pi functions

### ISSUE THREAD

**Issue by Clozent** [MichaelBykov/IntuitiveCalculator#2]
It would be awesome to have button for the Sigma/Pi functions (Sigma as the main, Pi through the pop-up menu) in the functions tab

**Comment by MichaelBykov** [comment]
Thank you for the feature request. I'll work on adding those functions in the next update.

**Comment by MichaelBykov** [comment]
The app has been updated and big sigma and pi functions have been added.
